### ISSUE TITLE
Property is ignored when there is no Display attribute

### ISSUE THREAD

**Issue by mickiewicz** [joseftw/EPiServer-ContentData-ToJson#21]
I was trying to serialize my Pages/Blocks and just figured out that some of my properties are ignored. It seems that when `Display` attribute is missing then property is ignored and it's not outputted. Just tested it and even empty `[Display]` attribute fix the issue.

**Comment by joseftw** [comment]
This is by design.
If you want to include properties that doesnt have the ```Display``` attribute you could use the```ContentSerializerIncludeAttribute```.

This is mentioned in the readme under ```Attributes```. https://github.com/joseftw/JOS.ContentSerializer#attributes

You can also write your own ```IPropertyResolver``` if you want even more control over which properties that should be included.

**Comment by mickiewicz** [comment]
Ahh, you are right!. I've read it couple of times but for some reason I've missed this part 🤦‍♂️ 

btw. Good job!
